[package]
name = "core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "vb_core"

[lints]
workspace = true

[dependencies]
proto = { path = "../proto" }

anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process", "io-util", "sync", "time", "rt"] }
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
