//! TypeScript binding assembly, enabled only with the `ts-export` feature.
#![cfg(feature = "ts-export")]

use ts_rs::TS as _;

use crate::error::CommandError;
use crate::{commands, envelope, error, sidecar};

/// Assembles the single-file TypeScript binding output for all proto types.
///
/// Each type declaration is prefixed with `export` so the output is a proper
/// ES module. Types are emitted in dependency order (referenced types before
/// referencing types) so the file is valid without any internal imports.
pub fn render() -> String {
    let sections: Vec<String> = vec![
        "// Auto-generated by `cargo run -p proto --features ts-export --bin gen_bindings`."
            .to_string(),
        "// Do not edit manually — re-run the generator to regenerate.".to_string(),
        String::new(),
        format!("export {}", error::ErrorCode::decl()),
        String::new(),
        format!("export {}", CommandError::decl()),
        String::new(),
        format!("export {}", sidecar::LogLevel::decl()),
        String::new(),
        format!("export {}", sidecar::LogMsg::decl()),
        String::new(),
        format!("export {}", sidecar::ProgressMsg::decl()),
        String::new(),
        format!("export {}", sidecar::ResultMsg::decl()),
        String::new(),
        format!("export {}", sidecar::ErrorMsg::decl()),
        String::new(),
        format!("export {}", sidecar::FromSidecar::decl()),
        String::new(),
        format!("export {}", envelope::CancelEnvelope::decl()),
        String::new(),
        format!("export {}", envelope::RequestEnvelope::decl()),
        String::new(),
        format!("export {}", envelope::ToSidecar::decl()),
        String::new(),
        format!("export {}", commands::SidecarStatus::decl()),
        String::new(),
        format!("export {}", commands::PingParams::decl()),
        String::new(),
        format!("export {}", commands::PingResult::decl()),
        String::new(),
        format!("export {}", commands::AppInfoParams::decl()),
        String::new(),
        format!("export {}", commands::AppInfoResult::decl()),
        String::new(),
        format!("export {}", commands::NewProjectParams::decl()),
        String::new(),
        format!("export {}", commands::NewProjectResult::decl()),
        String::new(),
        format!("export {}", commands::OpenProjectParams::decl()),
        String::new(),
        format!("export {}", commands::SaveSnapshotNowParams::decl()),
        String::new(),
        format!("export {}", commands::RecoveryReport::decl()),
        String::new(),
        format!("export {}", commands::OpenProjectResult::decl()),
        String::new(),
    ];
    sections.join("\n")
}
