//! IPC contract types shared between the Tauri app and the Python sidecar.
//!
//! All wire-format types are defined here. TypeScript equivalents are generated
//! by running `cargo test -p proto -- export_ts_bindings` which writes
//! `src/lib/ipc/types.ts` in the frontend project.
#![warn(missing_docs)]

pub mod commands;
pub mod envelope;
pub mod error;
pub mod sidecar;

pub use commands::{
    AppInfoParams, AppInfoResult, NewProjectParams, PingParams, PingResult, SidecarStatus,
};
pub use envelope::{CancelEnvelope, RequestEnvelope, ToSidecar};
pub use error::ErrorCode;
pub use sidecar::{ErrorMsg, FromSidecar, LogLevel, LogMsg, ProgressMsg, ResultMsg};

#[cfg(test)]
mod tests {
    use ts_rs::TS as _;

    /// Generates `src/lib/ipc/types.ts` from all proto types.
    ///
    /// Run with: `cargo test -p proto -- export_ts_bindings --nocapture`
    ///
    /// The file is the single source of truth for TypeScript IPC types consumed
    /// by the SvelteKit frontend (`src/lib/ipc/commands.ts`).
    #[test]
    fn export_ts_bindings() -> Result<(), Box<dyn std::error::Error>> {
        use crate::{commands, envelope, error, sidecar};

        let out_path =
            std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../src/lib/ipc/types.ts");

        std::fs::create_dir_all(out_path.parent().ok_or("no parent dir")?)?;

        // Assemble declarations in dependency order.  All types land in one
        // file so no import statements are needed between them.
        let sections: &[&str] = &[
            "// Auto-generated by `cargo test -p proto -- export_ts_bindings`.",
            "// Do not edit manually — re-run the test to regenerate.",
            "",
            &error::ErrorCode::decl(),
            "",
            &sidecar::LogLevel::decl(),
            "",
            &sidecar::LogMsg::decl(),
            "",
            &sidecar::ProgressMsg::decl(),
            "",
            &sidecar::ResultMsg::decl(),
            "",
            &sidecar::ErrorMsg::decl(),
            "",
            &sidecar::FromSidecar::decl(),
            "",
            &envelope::CancelEnvelope::decl(),
            "",
            &envelope::RequestEnvelope::decl(),
            "",
            &envelope::ToSidecar::decl(),
            "",
            &commands::SidecarStatus::decl(),
            "",
            &commands::PingParams::decl(),
            "",
            &commands::PingResult::decl(),
            "",
            &commands::AppInfoParams::decl(),
            "",
            &commands::AppInfoResult::decl(),
            "",
            &commands::NewProjectParams::decl(),
            "",
        ];

        std::fs::write(&out_path, sections.join("\n"))?;

        println!("TypeScript bindings written to {}", out_path.display());
        Ok(())
    }

    /// Round-trip serialisation smoke tests for the IPC envelope types.
    #[test]
    fn round_trip_request_envelope() -> Result<(), Box<dyn std::error::Error>> {
        use crate::envelope::{RequestEnvelope, ToSidecar};

        let msg = ToSidecar::Request(RequestEnvelope {
            request_id: "test-id".to_string(),
            command: "ping".to_string(),
            version: 1,
            payload: serde_json::json!({}),
        });

        let json = serde_json::to_string(&msg)?;
        let back: ToSidecar = serde_json::from_str(&json)?;

        let ToSidecar::Request(env) = back else {
            return Err("expected Request variant".into());
        };
        assert_eq!(env.command, "ping");
        assert_eq!(env.version, 1);
        Ok(())
    }

    #[test]
    fn round_trip_cancel_envelope() -> Result<(), Box<dyn std::error::Error>> {
        use crate::envelope::{CancelEnvelope, ToSidecar};

        let msg = ToSidecar::Cancel(CancelEnvelope {
            request_id: "cancel-me".to_string(),
        });

        let json = serde_json::to_string(&msg)?;
        assert!(json.contains(r#""type":"cancel""#));

        let back: ToSidecar = serde_json::from_str(&json)?;
        let ToSidecar::Cancel(env) = back else {
            return Err("expected Cancel variant".into());
        };
        assert_eq!(env.request_id, "cancel-me");
        Ok(())
    }

    #[test]
    fn round_trip_from_sidecar_messages() -> Result<(), Box<dyn std::error::Error>> {
        use crate::sidecar::{ErrorMsg, FromSidecar, LogLevel, LogMsg, ProgressMsg, ResultMsg};
        use crate::ErrorCode;

        let progress = FromSidecar::Progress(ProgressMsg {
            request_id: "req-1".to_string(),
            step: "transcribe".to_string(),
            step_index: 1,
            step_count: 4,
            pct: 25,
            label: "Transcribing…".to_string(),
        });
        let json = serde_json::to_string(&progress)?;
        assert!(json.contains(r#""type":"progress""#));
        let _: FromSidecar = serde_json::from_str(&json)?;

        let log = FromSidecar::Log(LogMsg {
            request_id: None,
            level: LogLevel::Info,
            msg: "sidecar ready".to_string(),
        });
        let json = serde_json::to_string(&log)?;
        assert!(json.contains(r#""type":"log""#));
        assert!(json.contains(r#""level":"info""#));
        let _: FromSidecar = serde_json::from_str(&json)?;

        let result = FromSidecar::Result(ResultMsg {
            request_id: "req-2".to_string(),
            payload: serde_json::json!({ "pong": true }),
        });
        let json = serde_json::to_string(&result)?;
        assert!(json.contains(r#""type":"result""#));
        let _: FromSidecar = serde_json::from_str(&json)?;

        let error = FromSidecar::Error(ErrorMsg {
            request_id: Some("req-3".to_string()),
            code: ErrorCode::Cancelled,
            message: "user cancelled".to_string(),
        });
        let json = serde_json::to_string(&error)?;
        assert!(json.contains(r#""type":"error""#));
        assert!(json.contains(r#""code":"cancelled""#));
        let _: FromSidecar = serde_json::from_str(&json)?;

        Ok(())
    }

    #[test]
    fn error_code_snake_case_serialisation() -> Result<(), Box<dyn std::error::Error>> {
        use crate::ErrorCode;

        assert_eq!(
            serde_json::to_string(&ErrorCode::OverlappingWordCannotCut)?,
            r#""overlapping_word_cannot_cut""#
        );
        assert_eq!(
            serde_json::to_string(&ErrorCode::SidecarNotReady)?,
            r#""sidecar_not_ready""#
        );
        Ok(())
    }
}
