/**
 * Typed wrappers around Tauri's invoke() for every registered command.
 *
 * Types come from types.ts (auto-generated by `cargo run -p proto --features ts-export --bin gen_bindings`).
 */
import { invoke } from '@tauri-apps/api/core';
import type {
	AppInfoResult,
	AudioFormat,
	NewProjectResult,
	OpenProjectResult,
	PingResult,
	TranscriptFormat
} from './types';

/** Returns the application version and sidecar lifecycle status. */
export async function getAppInfo(): Promise<AppInfoResult> {
	return invoke<AppInfoResult>('get_app_info');
}

/** Sends a ping to the Python sidecar and returns `{pong: true}` on success. */
export async function pingSidecar(): Promise<PingResult> {
	return invoke<PingResult>('ping_sidecar');
}

/** Creates a new empty project file at `path`, locked to `sampleRate`. */
export async function newProject(path: string, sampleRate: number): Promise<NewProjectResult> {
	return invoke<NewProjectResult>('new_project', { params: { path, sample_rate: sampleRate } });
}

/** Opens an existing project; resolves with missing-track and recovery info. */
export async function openProject(path: string): Promise<OpenProjectResult> {
	return invoke<OpenProjectResult>('open_project', { params: { path } });
}

/** Triggers an immediate snapshot of the open project. */
export async function saveSnapshotNow(): Promise<void> {
	return invoke<void>('save_snapshot_now', { params: {} });
}

/**
 * Starts playback from `startSample`; `endSample` (default `null`) plays to the end of the
 * timeline. Playhead progress arrives via the `playhead_update` event; the natural stop emits
 * `playback_stopped`.
 */
export async function playFrom(startSample: bigint, endSample: bigint | null = null): Promise<void> {
	return invoke<void>('play_from', {
		params: { start_sample: startSample, end_sample: endSample }
	});
}

/** Pauses playback, retaining the last position (no `playback_stopped` event). */
export async function pause(): Promise<void> {
	return invoke<void>('pause', { params: {} });
}

/** Stops playback and emits `playback_stopped` with the last position. */
export async function stop(): Promise<void> {
	return invoke<void>('stop', { params: {} });
}

/**
 * Renders a single track and writes it to `outputPath`. The codec is selected by the file
 * extension; `format` is advisory. `mono` collapses the stereo render to mono.
 */
export async function exportTrack(
	trackId: number,
	outputPath: string,
	format: AudioFormat = 'flac',
	mono = false
): Promise<void> {
	return invoke<void>('export_track', {
		params: { track_id: trackId, output_path: outputPath, format, mono }
	});
}

/**
 * Renders the full mix and writes it to `outputPath`. The codec is selected by the file
 * extension; `format` is advisory. `mono` collapses the stereo render to mono.
 */
export async function exportMixed(
	outputPath: string,
	format: AudioFormat = 'flac',
	mono = false
): Promise<void> {
	return invoke<void>('export_mixed', {
		params: { output_path: outputPath, format, mono }
	});
}

/**
 * Writes the project transcript to `outputPath`. The format is selected by the file extension;
 * `format` is advisory. `includeCutWords` includes words cut from the timeline.
 */
export async function exportTranscript(
	outputPath: string,
	format: TranscriptFormat = 'vtt',
	includeCutWords = false
): Promise<void> {
	return invoke<void>('export_transcript', {
		params: { output_path: outputPath, format, include_cut_words: includeCutWords }
	});
}
