/**
 * Typed wrappers around Tauri's invoke() for every registered command.
 *
 * Types come from types.ts (auto-generated by `cargo test -p proto -- export_ts_bindings`).
 * The generated file declares types without `export`, making them globally available
 * as TypeScript ambient types throughout the project — no import needed here.
 */
import { invoke } from '@tauri-apps/api/core';

/** Returns the application version and sidecar lifecycle status. */
export async function getAppInfo(): Promise<AppInfoResult> {
	return invoke<AppInfoResult>('get_app_info');
}

/** Sends a ping to the Python sidecar and returns `{pong: true}` on success. */
export async function pingSidecar(): Promise<PingResult> {
	return invoke<PingResult>('ping_sidecar');
}
