/**
 * Typed wrappers around Tauri's invoke() for every registered command.
 *
 * Types come from types.ts (auto-generated by `cargo run -p proto --features ts-export --bin gen_bindings`).
 */
import { invoke } from '@tauri-apps/api/core';
import type { AppInfoResult, NewProjectResult, OpenProjectResult, PingResult } from './types';

/** Returns the application version and sidecar lifecycle status. */
export async function getAppInfo(): Promise<AppInfoResult> {
	return invoke<AppInfoResult>('get_app_info');
}

/** Sends a ping to the Python sidecar and returns `{pong: true}` on success. */
export async function pingSidecar(): Promise<PingResult> {
	return invoke<PingResult>('ping_sidecar');
}

/** Creates a new empty project file at `path`, locked to `sampleRate`. */
export async function newProject(path: string, sampleRate: number): Promise<NewProjectResult> {
	return invoke<NewProjectResult>('new_project', { params: { path, sample_rate: sampleRate } });
}

/** Opens an existing project; resolves with missing-track and recovery info. */
export async function openProject(path: string): Promise<OpenProjectResult> {
	return invoke<OpenProjectResult>('open_project', { params: { path } });
}

/** Triggers an immediate snapshot of the open project. */
export async function saveSnapshotNow(): Promise<void> {
	return invoke<void>('save_snapshot_now', { params: {} });
}
