/**
 * Typed listeners for the Tauri events the backend emits.
 *
 * Payload types come from types.ts (auto-generated by `cargo run -p proto --features ts-export
 * --bin gen_bindings`).
 */
import { listen, type UnlistenFn } from '@tauri-apps/api/event';
import type { PlaybackStopped, PlayheadUpdate } from './types';

/**
 * Subscribes to `playhead_update` events emitted during playback. Resolves with an unlisten
 * function; call it when the handler goes out of scope.
 */
export async function onPlayheadUpdate(
	handler: (payload: PlayheadUpdate) => void
): Promise<UnlistenFn> {
	return listen<PlayheadUpdate>('playhead_update', (event) => handler(event.payload));
}

/**
 * Subscribes to `playback_stopped` events (natural end or user stop). Resolves with an unlisten
 * function; call it when the handler goes out of scope.
 */
export async function onPlaybackStopped(
	handler: (payload: PlaybackStopped) => void
): Promise<UnlistenFn> {
	return listen<PlaybackStopped>('playback_stopped', (event) => handler(event.payload));
}
