// Auto-generated by `cargo test -p proto -- export_ts_bindings`.
// Do not edit manually — re-run the test to regenerate.

type ErrorCode = "overlapping_word_cannot_cut" | "track_has_cuts_cannot_align" | "last_track_cannot_remove" | "track_name_empty" | "track_name_duplicate" | "speaker_name_empty" | "speaker_name_duplicate" | "model_not_available" | "low_confidence_transcript" | "file_not_found" | "export_unsupported_format" | "cancelled" | "sidecar_not_ready" | "unknown_command" | "internal_error" | "unknown";

type LogLevel = "debug" | "info" | "warn" | "error";

type LogMsg = { 
/**
 * UUIDv4 of the originating request, or `null` for process-level messages.
 */
request_id: string | null, 
/**
 * Severity level.
 */
level: LogLevel, 
/**
 * Log message text.
 */
msg: string, };

type ProgressMsg = { 
/**
 * UUIDv4 of the originating request.
 */
request_id: string, 
/**
 * Name of the current pipeline step (e.g. `"transcribe"`).
 */
step: string, 
/**
 * Zero-based index of the current step within the pipeline.
 */
step_index: number, 
/**
 * Total number of steps in the pipeline.
 */
step_count: number, 
/**
 * Completion percentage for the current step (0–100).
 */
pct: number, 
/**
 * Human-readable label for the current step, suitable for display in the UI.
 */
label: string, };

type ResultMsg = { 
/**
 * UUIDv4 of the originating request.
 */
request_id: string, 
/**
 * Command-specific result payload.
 */
payload: unknown, };

type ErrorMsg = { 
/**
 * UUIDv4 of the originating request, or `null` for process-level errors.
 */
request_id: string | null, 
/**
 * Machine-readable error code.
 */
code: ErrorCode, 
/**
 * Human-readable error description (not shown directly in the UI; used for logging).
 */
message: string, };

type FromSidecar = { "type": "ready" } | { "type": "progress" } & ProgressMsg | { "type": "log" } & LogMsg | { "type": "result" } & ResultMsg | { "type": "error" } & ErrorMsg;

type CancelEnvelope = { 
/**
 * UUIDv4 of the request to cancel.
 */
request_id: string, };

type RequestEnvelope = { 
/**
 * UUIDv4 identifying this request; echoed in every response.
 */
request_id: string, 
/**
 * Snake-case command name (e.g. `"transcribe_track"`).
 */
command: string, 
/**
 * Command schema version; increment on breaking param changes.
 */
version: number, 
/**
 * Command-specific parameters as a JSON object.
 */
payload: unknown, };

type ToSidecar = { "type": "request" } & RequestEnvelope | { "type": "cancel" } & CancelEnvelope;

type SidecarStatus = "ready" | "not_started" | "error";

type PingParams = Record<string, never>;

type PingResult = { 
/**
 * Always `true`; confirms the sidecar round-trip succeeded.
 */
pong: boolean, };

type AppInfoParams = Record<string, never>;

type AppInfoResult = { 
/**
 * Application version string (semver, from `Cargo.toml`).
 */
version: string, 
/**
 * Current lifecycle state of the Python sidecar.
 */
sidecar_status: SidecarStatus, };

type NewProjectParams = { 
/**
 * Absolute filesystem path for the `.vocalboard` project file.
 */
path: string, 
/**
 * Project sample rate in Hz, locked at creation (e.g. 48000).
 *
 * Any integer rate is accepted; 48000 is the default in the UI.
 */
sample_rate: number, };
