// Auto-generated by `cargo run -p proto --features ts-export --bin gen_bindings`.
// Do not edit manually — re-run the generator to regenerate.

export type ErrorCode = "overlapping_word_cannot_cut" | "track_has_cuts_cannot_align" | "last_track_cannot_remove" | "track_name_empty" | "track_name_duplicate" | "speaker_name_empty" | "speaker_name_duplicate" | "model_not_available" | "low_confidence_transcript" | "file_not_found" | "export_unsupported_format" | "audio_io_error" | "cancelled" | "sidecar_not_ready" | "unknown_command" | "internal_error" | "project_file_exists" | "project_file_not_found" | "project_open_failed" | "no_project_open" | "invalid_params" | "unknown";

export type CommandError = { 
/**
 * Machine-readable error code (the Paraglide message key).
 */
code: ErrorCode, 
/**
 * Human-readable description for logs/diagnostics; not UI-facing.
 */
message: string, };

export type LogLevel = "debug" | "info" | "warn" | "error";

export type LogMsg = { 
/**
 * UUIDv4 of the originating request, or `null` for process-level messages.
 */
request_id: string | null, 
/**
 * Severity level.
 */
level: LogLevel, 
/**
 * Log message text.
 */
msg: string, };

export type ProgressMsg = { 
/**
 * UUIDv4 of the originating request.
 */
request_id: string, 
/**
 * Name of the current pipeline step (e.g. `"transcribe"`).
 */
step: string, 
/**
 * Zero-based index of the current step within the pipeline.
 */
step_index: number, 
/**
 * Total number of steps in the pipeline.
 */
step_count: number, 
/**
 * Completion percentage for the current step (0–100).
 */
pct: number, 
/**
 * Human-readable label for the current step, suitable for display in the UI.
 */
label: string, };

export type ResultMsg = { 
/**
 * UUIDv4 of the originating request.
 */
request_id: string, 
/**
 * Command-specific result payload.
 */
payload: unknown, };

export type ErrorMsg = { 
/**
 * UUIDv4 of the originating request, or `null` for process-level errors.
 */
request_id: string | null, 
/**
 * Machine-readable error code (the Paraglide message key).
 */
code: ErrorCode, 
/**
 * Human-readable description for logs/diagnostics; not UI-facing.
 */
message: string, };

export type FromSidecar = { "type": "ready" } | { "type": "progress" } & ProgressMsg | { "type": "log" } & LogMsg | { "type": "result" } & ResultMsg | { "type": "error" } & ErrorMsg;

export type CancelEnvelope = { 
/**
 * UUIDv4 of the request to cancel.
 */
request_id: string, };

export type RequestEnvelope = { 
/**
 * UUIDv4 identifying this request; echoed in every response.
 */
request_id: string, 
/**
 * Snake-case command name (e.g. `"transcribe_track"`).
 */
command: string, 
/**
 * Command schema version; increment on breaking param changes.
 */
version: number, 
/**
 * Command-specific parameters as a JSON object.
 */
payload: unknown, };

export type ToSidecar = { "type": "request" } & RequestEnvelope | { "type": "cancel" } & CancelEnvelope;

export type SidecarStatus = "ready" | "not_started" | "error";

export type PingParams = Record<string, never>;

export type PingResult = { 
/**
 * Always `true`; confirms the sidecar round-trip succeeded.
 */
pong: boolean, };

export type AppInfoParams = Record<string, never>;

export type AppInfoResult = { 
/**
 * Application version string (semver, from `Cargo.toml`).
 */
version: string, 
/**
 * Current lifecycle state of the Python sidecar.
 */
sidecar_status: SidecarStatus, };

export type NewProjectParams = { 
/**
 * Absolute filesystem path for the `.vocalboard` project file.
 */
path: string, 
/**
 * Project sample rate in Hz, locked at creation (e.g. 48000).
 *
 * Any integer rate is accepted; 48000 is the default in the UI.
 */
sample_rate: number, };

export type NewProjectResult = { 
/**
 * Sample rate locked at project creation (Hz).
 */
sample_rate: number, };

export type OpenProjectParams = { 
/**
 * Absolute path to the `.vocalboard` file to open.
 */
path: string, };

export type SaveSnapshotNowParams = Record<string, never>;

export type RecoveryReport = { 
/**
 * Row id of the journal row that failed to decode.
 */
failed_row: bigint, 
/**
 * Row id of the snapshot the project was rolled back to.
 */
snapshot_id: bigint, };

export type OpenProjectResult = { 
/**
 * Track ids whose source file could not be located (Missing-Files dialog is M6).
 */
missing_tracks: Array<number>, 
/**
 * `Some` iff a corrupt-journal recovery rolled the project back to a snapshot.
 */
recovery: RecoveryReport | null, };

export type AudioFormat = "flac" | "wav" | "mp3" | "ogg" | "aac";

export type TranscriptFormat = "vtt" | "markdown";

export type PlayFromParams = { 
/**
 * Project-timeline start position, in integer samples (`>= 0`, guarded at the handler).
 */
start_sample: bigint, 
/**
 * Exclusive end position; `null` (the default) plays to the end of the timeline.
 */
end_sample: bigint | null, };

export type PauseParams = Record<string, never>;

export type StopParams = Record<string, never>;

export type ExportTrackParams = { 
/**
 * Id of the track to render and export.
 */
track_id: number, 
/**
 * Absolute output-file path; its extension selects the codec.
 */
output_path: string, 
/**
 * Advisory format (defaults to `flac`); the extension wins at the handler.
 */
format: AudioFormat, 
/**
 * Collapse the stereo render to mono (mean of L + R) before encoding. Defaults to `false`.
 */
mono: boolean, };

export type ExportMixedParams = { 
/**
 * Absolute output-file path; its extension selects the codec.
 */
output_path: string, 
/**
 * Advisory format (defaults to `flac`); the extension wins at the handler.
 */
format: AudioFormat, 
/**
 * Collapse the stereo render to mono (mean of L + R) before encoding. Defaults to `false`.
 */
mono: boolean, };

export type ExportTranscriptParams = { 
/**
 * Absolute output-file path; its extension selects the format.
 */
output_path: string, 
/**
 * Advisory format (defaults to `vtt`); the extension wins at the handler.
 */
format: TranscriptFormat, 
/**
 * Include words that were cut from the timeline. Defaults to `false`.
 */
include_cut_words: boolean, };

export type PlayheadUpdate = { 
/**
 * Current playhead position on the project timeline, in integer samples.
 */
position_samples: bigint, };

export type PlaybackStopped = { 
/**
 * Final playhead position on the project timeline, in integer samples.
 */
position_samples: bigint, };
